services:
  # MySQL Database Service (Replaces Postgres)
  mysql-db:
    container_name: mysql-db-bsn
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: scribe
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: scribe
      MYSQL_PASSWORD: scribePassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - spring-demo
    restart: unless-stopped

  # MailDev (Email Testing)
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - spring-demo

  # Keycloak (Authentication Service)
  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - spring-demo
    command:
      - "start-dev"
    restart: unless-stopped

networks:
  spring-demo:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  keycloak:
    driver: local

