spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  datasource:
    url: jdbc:mysql://${MYSQL_SQL_HOST}:${MYSQL_SQL_PORT}/${MYSQL_SQL_DB}
    username: ${MYSQL_SQL_USERNAME}
    password: ${MYSQL_SQL_PASSWORD}
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        globally_quoted_identifiers: true
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  data:
    mongodb:
      uri: mongodb+srv://jayshreeupadhyay:gbvaj0702@scribecluster.9pa0j.mongodb.net/?retryWrites=true&w=majority&appName=ScribeCluster
      database: scribe

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_CLIENT_ID
            client-secret: YOUR_CLIENT_SECRET
            scope: email, profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_TOKEN_SECRET}
  access:
    duration:
      minute: ${JWT_ACCESS_TOKEN_DURATION_MINUTE}
      second: ${JWT_ACCESS_TOKEN_DURATION_SECOND}
    cookie-name: ${JWT_ACCESS_COOKIE_NAME}
  refresh:
    duration:
      day: ${JWT_REFRESH_TOKEN_DURATION_DAY}
      second: ${JWT_REFRESH_TOKEN_DURATION_SECOND}
    cookie-name: ${JWT_REFRESH_COOKIE_NAME}

logging:
  level:
    root: warn
    org.hibernate.SQL: trace
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.web: trace
    org.springframework.security: TRACE
    org.springframework: DEBUG
    org.springframework.transaction: TRACE
